services:
  portfolio-prod:
    image: ghcr.io/kilalo/nuxtjs-portfolio:latest
    container_name: nuxt-portfolio-prod
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
