export const useProjects = () => {
  const { t } = useI18n();

  const projects = computed(() => [
    {
      id: 10,
      title: t("projects.circularplace.title"),
      description: t("projects.circularplace.description"),
      img: "/circularplace-project.png",
      date: t("projects.circularplace.date"),
      technologies: [
        "NestJS",
        "Vue.js",
        "Docker",
        "Stripe",
        "Zitadel",
        "GitHub Actions",
      ],
      role: t("projects.circularplace.role"),
      link: "https://circularplace.fr",
      prod: true,
    },
    {
      id: 9,
      title: t("projects.capency.title"),
      description: t("projects.capency.description"),
      img: "/capency-project.png",
      date: t("projects.capency.date"),
      technologies: [
        "Angular",
        "MongoDB",
        "GitHub Actions",
        "Salesforce",
        "Google Wallet",
        "Apple Wallet",
      ],
      role: t("projects.capency.role"),
      prod: true,
      link: "https://dqe.tech/capency/",
    },
    {
      id: 8,
      title: t("projects.flit.title"),
      description: t("projects.flit.description"),
      img: "/flit-project.jpg",
      date: t("projects.flit.date"),
      technologies: ["Nest", "Angular", "Docker", "AWS"],
      role: t("projects.flit.role"),
      link: "https://flit.run/",
      prod: true,
    },
    {
      id: 7,
      title: t("projects.hguitare.title"),
      description: t("projects.hguitare.description"),
      img: "/hguitare-project.jpg",
      date: t("projects.hguitare.date"),
      technologies: ["Laravel", "Jquery", "Stripe"],
      role: t("projects.hguitare.role"),
      link: "https://www.hguitare.com/",
      prod: true,
    },
    {
      id: 6,
      title: t("projects.creuch.title"),
      description: t("projects.creuch.description"),
      img: "/creuch-project.jpg",
      date: t("projects.creuch.date"),
      technologies: ["Laravel", "Vue", "Mangopay"],
      role: t("projects.creuch.role"),
      link: "https://creuch.fr",
      prod: true,
    },
    {
      id: 1,
      title: t("projects.portfolio.title"),
      description: t("projects.portfolio.description"),
      img: "/kilalo-project.jpg",
      date: t("projects.portfolio.date"),
      technologies: ["Vue", "Nuxt"],
      role: t("projects.portfolio.role"),
      link: "https://kilalo.io",
      prod: true,
    },
    {
      id: 2,
      title: t("projects.movies.title"),
      description: t("projects.movies.description"),
      img: "/movies-project.jpg",
      date: t("projects.movies.date"),
      technologies: ["React", "React Native"],
      role: t("projects.movies.role"),
      prod: false,
    },
    {
      id: 3,
      title: t("projects.sportsvillage.title"),
      description: t("projects.sportsvillage.description"),
      img: "/sv-project.jpg",
      date: t("projects.sportsvillage.date"),
      technologies: ["Vue", "Nuxt", "Laravel", "Docker"],
      role: t("projects.sportsvillage.role"),
      link: "https://sports-village.com",
      prod: true,
    },
  ]);

  return { projects };
};
